Menu Category Items fix
tulibraries/manifold pull request #2131
Opened 2021-11-17 16:24 UTC by cdoyle-temple

Move login screen out of application layout--this allows us to login even if there is an error in the application layout
Simplifies menu-items exclusion of non-categories
Category name will now defer to label in view (the non-category did not respond to name)
Deprecation warning cleanups for specifying partials

2021-11-17 16:26 UTC, nomadicoder requested changes
Are you testing for the conditions that caused the failure we encountered?

2021-11-17 16:31 UTC, cdoyle-temple commented
No, just cleaning up so we can get to the longer term solution of separating these menu categories out. That will enable us to create appropriate tests.

2021-11-17 17:21 UTC, cdoyle-temple commented
Accidentally pushed up test investigations.

2021-11-18 15:35 UTC, nomadicoder approved these changes

2021-11-18 15:37 UTC, merged