Man 1169 create the ability to modify the order of document attachments to a webpage
tulibraries/manifold pull request #2301
Opened 2022-03-30 16:45 UTC by cdoyle-temple

2022-03-30 20:33 UTC, nomadicoder requested changes
See my in-line comment

2022-03-30 20:33 UTC, nomadicoder commented on app/views/webpages/home.html.erb
> +<% binding.pry %>
Do we need this?

2022-03-31 19:59 UTC, cdoyle-temple commented on app/views/webpages/home.html.erb
> +<% binding.pry %>
nope

2022-04-01 17:29 UTC, nomadicoder approved these changes

2022-04-01 17:29 UTC, merged