MAN-1281: Fix error when destroying external links.
tulibraries/manifold pull request #3096
Opened 2023-10-26 15:02 UTC by dkinzer

2023-10-26 15:16 UTC, cdoyle-temple requested changes

2023-10-26 15:16 UTC, cdoyle-temple commented on app/views/layouts/devise/sessions.html.erb
> +<% if Rails.env == "production" %>
@dkinzer We don't want these fields in production, only on local environments.

2023-10-26 15:23 UTC, cdoyle-temple commented
@dkinzer External links which are currently attached to another model (e.g. a Webpage) are now not being destroyed when the button is clicked. There's also no error message or other indication that I tried to destroy the link.

2023-10-26 17:58 UTC, dkinzer commented
@cdoyle-temple I addressed the issue and added a test to check that when a link is attached to another model the link will not get destroyed.

2023-10-26 18:04 UTC, dkinzer commented
> @dkinzer External links which are currently attached to another model (e.g. a Webpage) are now not being destroyed when the button is clicked. There's also no error message or other indication that I tried to destroy the link.

Just a note that in fact for the test you ran the link was not being destroyed.  But, that is the expected behavior for when a link is attached to a model.  The issue was that by removing the redirect, the notice was not appearing.  The fix was to made sure that the redirect happened inside the block that checks for external links in other models and not to happen at the end after `super` is  called that has it's own redirect.

2023-10-27 17:05 UTC, cdoyle-temple approved these changes

2023-10-27 17:05 UTC, merged